version: '3.7'
services:
  postgres:
    image: postgres:10.7-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - rest-api-blog

networks:
  rest-api-blog:
